name: senu
description: "A new Flutter project."
publish_to: 'none'  # Уберите эту строку, если хотите публиковать на pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  dio: ^5.0.0         # Версия Dio
  dio_cookie_manager: ^2.0.1 # Пакет для работы с cookie в Dio
  cookie_jar: ^3.0.0  
  video_player: ^2.9.2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.9
  provider: ^6.0.5
  sentry_flutter: ^8.12.0
  google_fonts: ^6.0.0
  jwt_decoder: ^2.0.1
  rflutter_alert: ^2.0.7
  lottie: ^3.1.3
  get_it: ^8.0.3
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/amanzat_logo.png
    - assets/animation/
    - assets/intro.mp4